---
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8011/eureka
      
server:
  port: ${PORT:${SERVER_PORT:0}}   # Select any available port if neither port nor server port are specified.

---
spring:
  profiles: sentence
server:
  port: 8020  
lucky-word: sentenceeee

---
spring:
  profiles: word

lucky-word: wordddddd
 
